// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOHskaRJTjGWKMTG-AaXpOFqEf-edwQ-c',
    appId: '1:480722260086:web:b21199da10a50ac9d48f57',
    messagingSenderId: '480722260086',
    projectId: 'todolisty',
    authDomain: 'todolisty-59172.firebaseapp.com',
    storageBucket: 'todolisty.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_JIuCndpaMm9uC-TewYKVpwYEaNBp-5A',
    appId: '1:480722260086:android:d00e2cad0d5d74d8d48f57',
    messagingSenderId: '480722260086',
    projectId: 'todolisty',
    storageBucket: 'todolisty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEm2Q-lo3YwCG35VXB01NRykMdTFakCWI',
    appId: '1:480722260086:ios:7bc1018533126b41d48f57',
    messagingSenderId: '480722260086',
    projectId: 'todolisty',
    storageBucket: 'todolisty.appspot.com',
    iosClientId: '480722260086-a8feg5idfuk79pda18m7kpiu529pbnr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEm2Q-lo3YwCG35VXB01NRykMdTFakCWI',
    appId: '1:480722260086:ios:2c456ba1f7fa2e32d48f57',
    messagingSenderId: '480722260086',
    projectId: 'todolisty',
    storageBucket: 'todolisty.appspot.com',
    iosClientId: '480722260086-1hnq2a3vdj5rdnkdobe1gk3k79l7s7e4.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
